# Generated by Django 6.0.3 on 2026-08-14 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('mpesa_code', models.CharField(blank=True, max_length=20, null=True)),
                ('till_number', models.CharField(default='5927622', max_length=20)),
                ('payment_type', models.CharField(choices=[('rent_deposit', 'Rent Deposit & Move-In'), ('viewing_fee', 'House Viewing Fee'), ('service_charge', 'Service Charge'), ('landlord_verification', 'Landlord Verification Fee')], default='rent_deposit', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending M-PESA Confirmation'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
